server:
  port: ${PORT:15013}

spring:
  application:
    name: demo-sync
  jackson:
    property-naming-strategy: SNAKE_CASE # since jackson 2.7
    time-zone: Asia/Ho_Chi_Minh

spring.kafka.bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:192.168.1.162:29093}
spring.kafka.properties.sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";}
spring.kafka.properties.security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
spring.kafka.properties.sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}

